name: Render HTML

on:
  schedule:
    - cron: '0 7 * * 0' # Runs every sunday at 7am
  workflow_dispatch:

jobs:
  generate-html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install click==8.1.7 iso8601==2.1.0 Jinja2==3.1.4 MarkupSafe==2.1.5 pugsql==0.2.4 python-dotenv==1.0.1 SQLAlchemy==1.4.52 xmltodict==0.13.0

    - name: Run render script
      run: python jobs/render.py

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add index.html
        if ! git diff-index --quiet HEAD --; then
          git commit -m 'Github Action: Render HTML'
          git push
        else
          echo "No changes to commit."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
